id: P010576
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-20 10:14:51.771721
source_metadata:
  id: bdr:W1KG1611
  title: ཀུན་མཁྱེན་ཆོས་འབྱུང་གནས་ཀྱི་གསུང་རྒྱུན་དྲི་མ་མེད་པ་བུང་བའི་དགའ་སྟོན་དགེ་འདུན་ཉི་ཤུའི་རྣམ་གཞག
  author: ''
  volumes:
    f88ab75d46e74e31ab7b5c5146457f46:
      image_group_id: I1KG1758
      title: ''
      volume_number: 1
      total_pages: 148
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
